version: '3.7'

services:

  app:
    image: node:20
    entrypoint: ["/bin/sh", "-c"]
    working_dir: '/app'
    depends_on:
      - rabbit
    volumes:
      - .:/app
    ports: 
      - 3001:3001
    command: |
      "
        npm install
        npm start
      "

  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
